export enum Endpoint {
    Aplicacion = 'Aplicacion',
    Banner = 'Banner',
    DocumentoDigitales = 'DocumentoDigital',
    DocumentoDigitalesDescargar = 'DocumentoDigital/Descargar',
    DocumentoDigitalCrearCarpeta = 'DocumentoDigital/crearCarpeta',
    DocumentoDigitalCrearArchivo = 'DocumentoDigital/crearArchivo',
    DocumentoVideo = 'DocumentoVideo',
    DocumentoVideoCrearCarpeta = 'DocumentoVideo/crearCarpeta',
    DocumentoVideoCrearArchivo = 'DocumentoVideo/crearArchivo',
    EnlaceInteres = 'EnlaceInteres',
    Evento = 'Evento',
    Menu = 'Menu',
    Popup = 'Popup', 
    Rol = 'Rol', 
    RolMenu = 'RolMenu',
    RolAplicacion = 'RolAplicacion',
    RolUsuario = 'RolUsuario',
    SubMenu = 'Submenu',
    SubMenuHijo = 'Submenuhijo',
    Usuario = 'Usuario', 
    Video = 'DocumentoVideo', 
}